AWSTemplateFormatVersion: 2010-09-09
Description: Main template
Resources:
  NetworkingStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./vpc-template.yml
  MySqlServiceStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        StackName:
          !GetAtt NetworkingStack.Outputs.StackName
        ContainerMemory: 2048
        ContainerCpu: 1024
        DBMasterUserName: sonarqube
      TemplateURL: ./mysql-template.yml
    DependsOn:
      - NetworkingStack
  SonarqubeServiceStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        StackName:
          !GetAtt NetworkingStack.Outputs.StackName
        ContainerMemory: 2048
        ContainerCpu: 1024
      TemplateURL: ./sonarqube-template.yml
    DependsOn:
      - NetworkingStack
      - MySqlServiceStack