AWSTemplateFormatVersion: 2010-09-09
Description: Main template
Resources:
  NetworkingStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./vpc-template.yml
  ServiceStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        StackName:
          !GetAtt NetworkingStack.Outputs.StackName
        ServiceName: Sonarqube
        ImageUrl: sonarqube:latest
        ContainerPort: 9000
        ContainerMemory: 2048
        ContainerCpu: 1024
        DesiredCount: 1
      TemplateURL: ./service-template.yml
    DependsOn:
      - NetworkingStack