AWSTemplateFormatVersion: 2010-09-09
Description: Main template
Resources:
  NetworkingStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        BastionKeyName: mmalerba
      TemplateURL: ./vpc-template.yml
  DbServiceStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        NetworkingStackName:
          !GetAtt NetworkingStack.Outputs.StackName
        DatabaseName: sonar
      TemplateURL: ./db-template.yml
    DependsOn:
      - NetworkingStack
  SonarqubeServiceStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        DBSecret:
          !GetAtt DbServiceStack.Outputs.DBSecret
        RDSEndpointAddress:
          !GetAtt DbServiceStack.Outputs.RDSEndpointAddress
        StackName:
          !GetAtt NetworkingStack.Outputs.StackName
        ServiceName: sonarqube
        ImageUrl: sonarqube
        ContainerMemory: 2048
        ContainerCpu: 1024
      TemplateURL: ./sonarqube-template.yml
    DependsOn:
      - DbServiceStack